### ISSUE TITLE
README missing .md 

### ISSUE THREAD

**Issue by AaronCheung430** [iHTCboy/iHTCboy.github.io#530]
Hi there, just came across your github, and found your README file is missing the .md format. As github is just showing the raw README file instead. Thanks

**Comment by iHTCboy** [comment]
@AaronCheung430 hello, because when Hexo generates articles, it will automatically convert all .md files to html. In order to avoid README.md being converted to html, the .md suffix is ​​removed.

**Comment by AaronCheung430** [comment]
Thanks, saw that in your blog as well.
